version: 2.1

executors:
  movie-ui-executor:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/movie-ui

jobs:
  test:
    executor: movie-ui-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-deps-{{ checksum "package.json" }}
          - npm-deps-
      - run:
          name: Install Node Dependencies
          command: npm i
      - run:
          name: Run Linting and Tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: npm-deps-{{ checksum "package.json" }}

  build_deploy:
    executor: movie-ui-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9e:9a:81:67:fb:7b:bc:d4:80:80:cf:e3:d6:eb:92:5d"
      - checkout
      - run:
          name: Bump package version
          command: |
            set -e
            git config user.name $CIRCLE_USERNAME
            git config user.email "work-mpconsultants@outlook.com"
            npm version patch -m  "Release version %s [ci skip]"
            git push origin master --tags
            echo 'export VERSION=$(npm run version --silent)' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name : Build & Deploy Docker Image
          command: |
            docker build -f ./build/prod/Dockerfile -t movie-ui:$VERSION .
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag movie-ui:$VERSION registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
            export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
            curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -d '{ "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" }]}' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY"

workflows:
  version: 2
  cd_pipeline:
    jobs:
      - test
      - build_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
