version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/movie-ui
    steps:
      - checkout
      - run: 
          name: Install Node dependencies
          command: npm i
      - run:
          name: Run linting and tests
          command: npm test
      - run:
          name : Build Docker Image
          command: docker build -t movie-ui:$CIRCLE_SHA1 .
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag movie-ui:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
            export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
            curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -d '{ "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" }]}' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY"